language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: HODLj/9/kfn8qSRnZT2x9i6P2nsN7G4AuNmXDtmXTUpRYyBBnM+zRBM/Ee0VK+C8PdEISxcZsb3mMiYQludZqMiWxbgdEwSzEk3979zXHGRtR341FO+6LAHJb0/RsZuJ7yCNGdjfYGzigv3g5AX7/CSbTB6OTG7zElMjLHeRoTv3gUUyWGF6VlTIwx3wQrbXSGNE0aEsFr0j0Tfjry/ZQTCt35XYmzsFQG+nPcsEKMS2t0wJvvK0M2a0U/7RnZyeYMEfp0tOYGYwd8CObc1CrntjiQ1fnKRq8x38HrWL0HvTCDJ63vTEFNj+qggK0RehQjssqzG6Tcfb/eOysXpsBGvXyjsAL0+ScGTTxhFa8rlwk3MyapPXmzAGiC+7ul2Ysa3o+mn70QrRpccp/JVpz0iZmmSWienksvVWQEFnquJ3lWdJm0Lal7fwKEoDyLNNvNMXa5+cAUp7jsVJmAJj+HFd6Poztphiwbg91Rih1BpNKpD6cKwnQPinHKjstHWVMoEQKDQWusJpn05FSNbtx0bOGEqBWVknvnjdDmbVVrNIZ2DyuykUFHSgXR2N1a0C2XTQVE31X6lKslEYdEp8LzEeUPj3BQWcIl7nPpdpjeC+T50UTgujdZRXg6A6GMBmPPU+gNNAELdbao8IYx3Cbt3Ko+oBBQzr1EMpKW86OrM=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
