language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: ExbVFE+0W9phh2GEARUzBqabv/iw+5udLvDROTr7ufb72XU4F5NuiizxYj+mwIWpHqOxkdnYPYsp/RiroaJmIn9tD0nuYWvbsZIjPB97KbTM/1Eh978NwTF4n7l9v7sTrmVsCMD5pheVAi4edtVZX5s0nFmSZdfyYtJWNzEsTVfjgEKhW2aVUsuKIfauZ5g4MdsLTdjtxsYU3YTziAdcWpN1ZIXJjyQHOjmmnyQWOHj0glclVoPTVkTC9FWsht/2x8aZRcRXNLlYLeoVlm6M2nTyxFWX76Ary4amCS3MYLrjbu3bFLTtl+Op6r3ojc1f060vtoZLTP5idSbhMBU8qfaUxMQRnbeJ+CF1XC7YW7UEy4y5OIjKi+NtEG+hu1V9jCOxxzBFpHo5jL/TAHWPuSTvbB5wA100bhfbeFVUik4xg5WgbdZKy67sNFQeGP4xsq+LPiAfccwwKw4HilqQWzUe6reCa/p3csBwQfBLHgZnociGscFfs21Mq7iEOT0NpIBlZvhieJGa0zhqrxbVuaNgxiawIkkr7Re2LunNx6UuJ5PgnDAtk+to8lc81TV665jgVJ0/1yYX/cJd0OwHcPDZB4ge0Vns/D1BywT/zZmnINUem8OwMyEMWWVpmdTgNBtVgS8r8JAJz78l4N6MiZtoYaZFr9zxwYaZmRaEROM=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
